### ISSUE TITLE
Examples 

### ISSUE THREAD

**Issue by unkcs** [XMDS/GlossHook#5]
Could you provide more examples of how to use it?

**Comment by XMDS** [comment]
@unkcs  Please wait a few days before I release a new version. It will have comments and docs for all APIs, including examples.  (It’s worth mentioning that AML is using GlossHook, which has been tested on many devices without problems),

**Comment by unkcs** [comment]
@XMDS I want to use armeabi-v7a and amr64-v8a in a build69 project for GTA SA, it seems to be similar to ARMHook
