### ISSUE TITLE
Fix please 

### ISSUE THREAD

**Issue by NewCosmoCoder** [XMDS/GlossHook#6]
Hello, this hook does not work well on Android 10, the game crashes, crashes when entering, I checked the same mod on 3 devices on Android 11 - 13, everything works perfectly, 10 errors and crashes.

**Comment by XMDS** [comment]
send your code

**Comment by XMDS** [comment]
Right here githud's markdown

**Comment by NewCosmoCoder** [comment]
I sent you the Cheat function for advertising in chat, even with one function it doesn’t work, other hooks work great, I need your hook because it works perfectly on all devices except 10 Android

**Comment by NewCosmoCoder** [comment]
I myself can’t understand what the problem is with Android 10 even.

Even with this code, your hook does not work on Android 10, but on other versions of Android everything works perfectly.

void *libAndroid = xdl_open(android.path, Asterial(RTLD_LAZY));
    while (!libAndroid) {
        libAndroid = xdl_open(android.path, Asterial(RTLD_LAZY));
		LOGERROR(Asterial("Номер Ошибки: 104"));
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }

GHook(xdl_sym(libAndroid, Asterial("ANativeWindow_getWidth"), nullptr), hook_getWidth, old_getWidth);
    GHook(xdl_sym(libAndroid, Asterial("ANativeWindow_getHeight"), nullptr), hook_getHeight, old_getHeight);

**Comment by NewCosmoCoder** [comment]
If you need help from me in correcting this error, write to me, I will help as best I can, I have root rights on my devices

**Comment by XMDS** [comment]
Check if the il2cpp + Astererial (0x2491FA8) address is valid and if it is located in the .got section.  Also, determine if reentrancy occurs in function hChat

**Comment by XMDS** [comment]
Android 10, do other HOOK APIs work?  For example InlineHook

**Comment by NewCosmoCoder** [comment]
I tried: DobbyHook and A64HookFunction.

And these hooks work perfectly.

**Comment by XMDS** [comment]
Send me a screenshot of your address in idapro.  Secondly, you should give me the Android Log information, where there are hook records.  Also, you should write the code to print the log at the beginning of the hChar function and see if it is executed into the hook function, where does it crash?

**Comment by NewCosmoCoder** [comment]
Okay, I'll output the log to the logs

**Comment by NewCosmoCoder** [comment]
Hello, I fixed a bug with Android 10 64 bit. 
I corrected the definition in Gloss_reg for 64-bit architecture (__aarch64__). 
Added the x30 field to the regs structure, since it is used for lr in ARM64. 
Moved cpsr to the end of the regs structure to match the standard register layout.

**Comment by NewCosmoCoder** [comment]
I have a request for you, can you give me your project GlossHook? 
I'm not going to distribute it as my own, I want to add new features and improvements, if you can give access to GitHub then I will update it.

**Comment by NewCosmoCoder** [comment]
У меня много устройств для тестирования и разработки.

**Comment by NewCosmoCoder** [comment]
I will try to update once a week and of course I will test everything I add.

**Comment by XMDS** [comment]
fix to 1.9.0
